### ISSUE TITLE
Sun Jan  6 12:42:26 2013 - Error loading plugin settings: Can't locate object method "settings" via package "Bucket::Plugin::topic" at ./bucket.pl line 3641.

### ISSUE THREAD

**Issue by Wozarib** [zigdon/xkcd-Bucket#12]
hi there!

The problem I have is as follows: 

Sun Jan  6 12:42:26 2013 - Error loading plugin settings: Can't locate object method "settings" via package "Bucket::Plugin::topic" at ./bucket.pl line 3641.

This is the only error I can see it logging :| 

The bot will connect to the control channel, but nothing else. If i say anything in the control channel, it sends it into a tailspin, and it generates a huge log file, viewable here:

http://weezel.co.uk/files/logs.txt

It seems to generate "delayed messages" which it seems to multiply so that each new line is longer than the last.

I've tried removing the topic plugin (as it could see it referenced in the error) but the bot still only joins the control channel, and will generate huge log files if triggered in any way

**Comment by dgw** [comment]
I've never seen this happen, in roughly two years of running Bucket. Going to close the issue, seeing as it's been open for over 4 years. If it's still a problem, @Wozarib, feel free to come back and let us know.
