### ISSUE TITLE
Quotes plugin double-strips colon phrases

### ISSUE THREAD

**Issue by cincodenada** [zigdon/xkcd-Bucket#28]
Today someone tried to quote the following line:

```
<iirelu> ladymondegreen: solution: enslave grandmothers
```

And Bucket only remembered "enslave grandmothers".  I believe this is because before handing the `%bag` to the quotes plugin, Bucket strips out any addressee (at [bucket.pl#L304](https://github.com/zigdon/xkcd-Bucket/blob/master/bucket.pl#L304)), so the quotes plugin receives only "solution: enslave grandmothers" and dutifully strips out what it sees as a nick address.

Is this second stripping ever necessary, if Bucket already pulls out the nick?  In a cursory glance it seems that the quotes plugin could just not strip any nicks, but I'm not familiar enough with the codebase to know that for sure.  I may play with it later to see.

**Comment by dgw** [comment]
I don't know if @cincodenada ever played with this "later" (I said, speaking nearly 4 years later), but I can confirm it is still an issue. Going to self-assign this so I'll remember to work on it.
