### ISSUE TITLE
Add support for using a server password

### ISSUE THREAD

**Issue by dgw** [zigdon/xkcd-Bucket#49]
As far as I can tell, from searching through the code and the documentation, Bucket doesn't support servers with passwords. The IRC library does, though, and I've hacked that function into my copy of bucket.pl.

I'm happy to submit a pull request for this, if it's something that could get merged, after I've had time to run my tweaked version for a while. Is there anything I should be aware of besides adding the `Password` element to the IRC connection data (`$irc->yield`)? Like maybe a default value besides the obvious `""` (empty string)?

**Comment by zigdon** [comment]
That seems like it should be it.
