### ISSUE TITLE
Removing and adding a value in a large var results in using only the new value(s) until restart

### ISSUE THREAD

**Issue by dgw** [zigdon/xkcd-Bucket#62]
I haven't figured out yet where to look for this, so filing an issue in case anyone else has ideas.

**Example case 1**

```
[18:58:08] <&Kaede> Tales of Tents: Pokemon of the Amazing Ace
[18:58:22] <~dgw> Kaede: what was that
[18:58:22] <&Kaede> dgw: That was '!tales' (#2195): <reply> Tales of $Nouns: $Noun of the $Adjective $Noun;  vars used: { 'Noun' => [ 'Pokemon', 'Ace' ], 'Nouns' => [ 'Tents' ], 'Adjective' => [ 'Amazing' ]};.
[18:58:42] <&Kaede> dgw removed a value from $noun in dgw: pokemon
[18:58:53] <&Kaede> dgw added a value to $noun in dgw: Pokémon
[19:01:26] <+JAKQ> !fate
[19:01:26] <&Kaede> Fate/Read Pokémon
[19:01:34] <+JAKQ> !tales
[19:01:34] <&Kaede> Tales of Pokémons: Pokémon of the Strict Pokémon
[19:01:38] <~dgw> Uh
[19:01:47] <~dgw> Kaede: restart
[19:01:47] <&Kaede> Restarting at dgw's request
[19:01:47] <&Kaede> Okay, dgw, I'll be right back.
[19:03:28] <~dgw> !fate
[19:03:28] <&Kaede> Fate/Finance Pepsi
```

**Example case 2**

```
[19:07:34] <&Kaede> JAKQ removed a value from $noun in JAKQ: sata andagi
[19:07:49] <&Kaede> JAKQ added a value to $noun in JAKQ: saataa andagi
[19:08:06] <~dgw> Slyphoria's obsession with foods strikes again
[19:08:11] <~dgw> !fate
[19:08:12] <&Kaede> Fate/Furry Saataa Andagi
[19:08:39] <@JAKQ> !tales
[19:08:40] <&Kaede> Tales of Saataa Andagis: Saataa Andagi of the Ruined Saataa Andagi
[19:08:44] <&Kaede> Restarting at dgw's request
[19:08:52] JAKQ furrows eyebrows at that bug
```

**Comment by zigdon** [comment]
Hmm, looks like the large var cache is getting corrupt? One way around could be to trigger a rebuild of the cache for that var any time we make changes to it.

**Comment by dgw** [comment]
I've just run into this again after some cleanup on `$band`.

Removed a value or two, then tried to add one back. "I had it that way!" Meanwhile, only recently learned band names were being used in triggered factoids.

Restarted, then added the value manually. Every factoid that uses `$band` used that value until I restarted again.

Gonna have to dig in and implement that cache rebuilding… this is ridiculous.

**Comment by dgw** [comment]
I'm still at a loss on this. So far as I can tell, my instance's `$band` has precisely one value in it, but not even the code that's supposed to refill the cache when it gets low is triggering, according to Bucket's log file. After building a very simple test script I tried changing the check `@{$record->{cache}} < (&config("var_limit") or 3)` to `@{$record->{cache}} < (&config("var_limit") || 3)` (because `||` in the test script let the nonzero value through, but `or` did not).

If the size check is working as expected, then the other possibility is that `exists $record->{cache}` fails. And that's not really a possibility, is it?

Script and result for reference:

````bash
23:32 $ cat test.pl
my $zero = 0;
my $nonzero = 3;

if (1 < ($zero || $nonzero)) {
  print "less";
} else {
  print "not less";
}

print "\n";
23:32 $ perl test.pl
less
````

**Comment by dgw** [comment]
This morning turned up an interesting clue. (I should look into this more often…has it really been 7 months since I last bothered?)

I added a couple of debug prints to check for `$record->{cache}` or `$record->{vals}` and print their contents if they exist.

Before removing/adding a value from `$band` (which is quite large and is normally pulled from cache):

````
<Bucket> 'Band' is cached: case in point I'm Excited Now except for rekt racism isn't
         cool it's absolutely adorable i'm in 4 better font too i luv trash all what
         16 values in cache
````

After removing/adding a value from `$band`:

````
<Bucket> 'Band' is cached: case in point I'm Excited Now except for rekt racism isn't
         cool it's absolutely adorable i'm in 4 better font too i luv trash all what
         16 values in cache
<Bucket> 'Band' has vals: I Speak Java
````

The value that I added was placed in the `vals` array, as if `$band` was a short replaceable with all its values kept in memory. That then overrides future use of the value cache; Bucket never checks to see if `vals` is running low, because it's meant to be a list of every value in the var. And so it keeps using only the new value(s).

When Bucket learns a band name on his own, this doesn't happen. That doesn't make any sense to me… In `add_new_band`, the check is `if ( exists $replacables{$band_var}{vals} )` — and the new band name goes into the cache, as long as `{vals}` hasn't been created by removing and adding a value manually. But in the `add value` command, the functionally identical check `if ( exists $replacables{$var}{vals} )` appears to result in adding the new value to `{vals}` instead of `{cache}`, breaking the variable.

Could the line `foreach my $v ( @{$replacables{$var}{vals}} )` be forcing `{vals}` to exist? I tested this theory:

```` Perl
# script testexists.pl
my %replacables;
$replacables{var}{cache} = ();
if ( exists $replacables{var}{cache} ) {
    print "sanity check: cache exists\n";
}

if ( exists $replacables{var}{vals} ) {
    print "vals exists before foreach\n";
} else {
    print "vals does not exist before foreach\n";
}

foreach my $v ( @{$replacables{var}{vals}} ) {
    print "iterated over a val\n";
}

if ( exists $replacables{var}{vals} ) {
    print "vals exists after foreach\n";
} else {
    print "vals does not exist after foreach\n";
}
````

The result?

````
$ perl testexists.pl
sanity check: cache exists
vals does not exist before foreach
vals exists after foreach
````

I finally found [at least one cause of] the bug! But… Perl, why do you do that?! Don't just create hash elements out of nothing because you saw a `foreach`! 💢  ಠ_ಠ

Well, now I have a basis for writing and testing a patch to fix this annoying bug. PR to come Soon™.

**Comment by zigdon** [comment]
It does make total sense - perl instantiates values as needed. We looked up
the value in vals, and declared it's an array ref, so perl made it so.

Nice catch :)

**Comment by dgw** [comment]
I now have learned why one of my oldest coding buddies says that Perl has "odd" semantics. I'll get the fix for this pushed up in a PR soon-ish, when I've got some time back at a computer.
