### ISSUE TITLE
Join/Part doesn't parse channel names properly

### ISSUE THREAD

**Issue by dgw** [zigdon/xkcd-Bucket#73]
This week I came across a channel that I couldn't tell Bucket to join a channel that wasn't handled properly:

```
<dgw> Kaede: join #nkc48.lounge
<Kaede> joining #nkc48 at dgw's request
<Kaede> dgw: joining #nkc48
```

I'm guessing it's because the join/part command regex doesn't allow for `.` in channel names: `/^(join|part) (#[-\w]+)(?: (.*))?/i`

This is because `[-\w]` expands to `[-A-Za-z0-9_]`, which means anything that isn't in that set (or a hyphen) will end the match. (It also won't handle channels that start with `&`, for example, but maybe it would be too much trouble to handle the server's `CHANTYPES` response.)

Working on a better regex right now, possibly using `\S` instead of `\w` due to the fact that basically any non-whitespace character seems to be valid in channel names on a lot of IRCds… but comments and suggestions are welcome. I'm going to test for quite a while before I consider any solution PR-ready.

**Comment by zigdon** [comment]
Ideally, parsing `CHANTYPES` might be the best idea. But otherwise, `\S` might be sufficient.
