### ISSUE TITLE
logfile doesn't get written to for long periods of time

### ISSUE THREAD

**Issue by dgw** [zigdon/xkcd-Bucket#74]
`tail -f /path/to/bucketlog` is basically useless, since it might take minutes or hours to update. And when it does update, it dumps out a ton of lines.

When I shut down my Bucket instance, it also throws away some log data that is never written out. (I do shut it down with `service bucket stop` on Ubuntu, so Bucket might not be given the chance to clean up before it exits.)

I'm looking into this, because I really want to be able to tail Bucket's log to find more info on another issue.

**Comment by SpicyLemon** [comment]
In the past, when I've seen this, it's because the file is being opened once, written to a lot, then closed way later (if ever).  The solution I've found is to open and close the logfile with each write.

Alternatively, I've never tried it, but you might be able to do a print LOG $|; to flush the buffer.  I know that works when printing to the screen, but I've never tried it on a file.

**Comment by dgw** [comment]
Did a little research. Apparently, file I/O in Perl is done [through a buffering layer](http://perl.plover.com/FAQs/Buffering.html), including appended writes. It only flushes the new log lines out to disk when the write buffer fills up by default, and the buffer is typically multiple kilobytes long, so it can take a fair amount of chatting to fill.

Opening and closing the log file for each write would require a bit more code refactoring than I want to do, given that currently Bucket opens the log file and just hangs on to the filehandle, checking if it needs to be reopened every so often. But I think there's another solution called "making the filehandle _hot_", described in that buffering FAQ page, that will solve this by making Perl flush the buffer on every write. Going to test tonight, and submit a PR if it solves the issue.

I bet it will. The trick you suggested with `$|` seems to be related, @SpicyLemon, as part of making the filehandle hot is setting `$|=1`.

**Comment by dgw** [comment]
I honestly have no idea why this is still open. The PR to fix it was merged months ago…
