### ISSUE TITLE
$vehicle et $room not working in source

### ISSUE THREAD

**Issue by genewitch** [zigdon/xkcd-Bucket#81]
vehicle and room are unknown even though the wiki says they're available. if you say bucket: testfactoid \<reply\> foo $vehicle drives into $room

and then 

\<me\>:  testfactoid

bucket: foo $vehicle drives into $room

**Comment by dgw** [comment]
The wiki is specifically about #xkcd's instance of Bucket, so not all variables and other instance-specific constructs will be available in your own instance cloned from GitHub.

If you want `$vehicle` and `$room` to work in your own instance, you'll have to `Bucket: create var vehicle` and `Bucket: create var room`, and then use `add value` commands to populate each variable. If you want a quick start, head to Foonetic and `/msg Bucket list var room` (or `list var vehicle`); it's trivial from there to prefix each value with `/msg Bucket add value vehicle ` (or `add value room`), then paste the whole shebang into your IRC client and have your Bucket learn all the values. Beware of potential flooding, of course. :)

@zigdon please close
