### ISSUE TITLE
Bucket only gets 'bananas' in PM

### ISSUE THREAD

**Issue by dgw** [zigdon/xkcd-Bucket#86]
A user experimenting with factoids in PM on my instance noted that `$getitem` only ever returns "bananas" in PM. @zigdon is this intended behavior, so inventory factoids don't work outside a channel, or should it be fixed?

**Comment by zigdon** [comment]
IIRC that's by design, since we didn't want someone draining the stash in
PM and affecting the inventory in channel.

**Comment by dgw** [comment]
If it's intended, then that's fine. Closing.
